Repository marc-pan/kg-cicada, pull requests merged in 2024-10, with the labels that each got.

#13 issue#12: new example
  subproject/cash-card-application/build.gradle
  subproject/cash-card-application/src/main/java/kg/ergo/demo/CashCard.java
  subproject/cash-card-application/src/main/java/kg/ergo/demo/CashCardController.java
  subproject/cash-card-application/src/main/java/kg/ergo/demo/CashCardRepository.java
  subproject/cash-card-application/src/main/java/kg/ergo/demo/SecurityConfig.java
  subproject/cash-card-application/src/main/resources/schema.sql
  subproject/cash-card-application/src/test/java/kg/ergo/demo/CashCardApplicationTests.java
  subproject/cash-card-application/src/test/java/kg/ergo/demo/CashCardJsonTest.java
  subproject/cash-card-application/src/test/resources/data.sql
  subproject/cash-card-application/src/test/resources/kg/ergo/demo/expected.json
  subproject/cash-card-application/src/test/resources/kg/ergo/demo/list.json
Labels: enhancement

#16 Semantic version
  settings.gradle
Labels: enhancement

#19 ci: disable publish
  .github/workflows/gradle.yml
Labels: enhancement

#24 ci: bump new version
  archieve/pom.xml
Labels: dependencies

#25 security fixes
  machine_learning/prompt_library/english_grammar_genie.py
  scripts/dpx/dph_install.sh
Labels: enhancement

#26 Create SECURITY.md
  SECURITY.md
Labels: enhancement

#27 Fix code scanning alert no. 1: Cross-site scripting
  subproject/service-b/build.gradle
  subproject/service-b/src/main/java/com/ibm/app/demo/client/ServiceController.java
Labels: enhancement

#28 add python notebooks
  pyproject/notebooks/Mistral_application.ipynb
  pyproject/notebooks/Ollama_notebook.ipynb
  scripts/open-metadata/docker-compose.yml
Labels: enhancement

#32 doc: add a document about how-to for open metadata instance
  scripts/open-metadata/HOW-TO.md
Labels: documentation
